### PR TITLE
Update llm_glm6b.py

### PR DESCRIPTION
**Pull request by serfan**
解决加载chatglm2爆显存的问题

### CODE REVIEW

**Comment by serfan** [comment]
ok

**Comment by l15y** [comment]
你的修改会导致不能用cuda以外的设备推理
已经在https://github.com/wenda-LLM/wenda/commit/517794a2ea44fc070bba6005f0b3d33a8c1e4cd8修复

**Comment by serfan** [comment]
6G显卡爆显存的问题依然存在。
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 6.00 GiB total capacity; 5.34 GiB already allocated; 0 bytes free; 5.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by serfan** [comment]
加载模型的时候做一个判断就可以解决，当然我这里没有更多设备测试。我的显卡是3060 6G
`if device == 'cuda':
        model = AutoModel.from_pretrained(settings.llm.path, local_files_only=True, trust_remote_code=True,revision="v1.1.0").cuda()
    else:
        model = AutoModel.from_pretrained(settings.llm.path, local_files_only=True, trust_remote_code=True, device=device, revision="v1.1.0")`

**Pull request closed without merging**
